neuvector/docs

- user/pages/03.configuration/01.console/docs.md
Fix a syntax issue preventing a link from rendering correctly
> Fix Markdown Syntax

- user/pages/05.policy/04.groups/docs.md
- user/pages/05.policy/05.networkrules/docs.md
- user/pages/05.policy/06.processrules/docs.md
- user/pages/05.policy/09.dlp/docs.md
- user/pages/05.policy/11.customcompliance/docs.md
- user/pages/05.policy/13.usingcrd/docs.md
- user/pages/06.scanning/01.scanning/02.compliance/docs.md
- user/pages/06.scanning/01.scanning/docs.md
How about unifying the first letter capitalization for the attack names, e.g. SYN flood attack -> SYN Flood attack. 
Currently some are capitalized, some not.
> 2 typo fixes and alphabetic attack order

- user/pages/06.scanning/02.registry/docs.md
Making clear that NeuVector registry scanning capabilities only scan changes and additions from the previous scanning activity, and don't scan every single image in the registry on each sweep.
> Update docs.md - Note that reg scanning scans deltas

- docusaurus.config.js
- src/css/index.css
- versioned_docs/version-5.2/13.special/04.docker/04.docker.md
- versioned_docs/version-5.3/01.basics/01.basics.md
- versioned_docs/version-5.3/02.deploying/01.production/01.configmap/01.configmap.md
- versioned_docs/version-5.3/02.deploying/01.production/01.production.md
- versioned_docs/version-5.3/02.deploying/01.production/02.operators/02.operators.md
- versioned_docs/version-5.3/02.deploying/04.openshift/04.openshift.md
- versioned_docs/version-5.3/02.deploying/09.airgap/09.airgap.md
- versioned_docs/version-5.3/03.configuration/03.customui/03.customui.md
- versioned_docs/version-5.3/06.scanning/02.registry/01.harbor/01.harbor.md
The following corrections have been applied to fix issues due to the Docusaurus migration:
- Configuration: set `routeBasePath` to `/`
- Configuration: change footer copyright to `SUSE NeuVector`
- Remove broken link in 5.2 version
- Update neuvector images version to `5.3.2` in 5.3 version
- CSS updated to be adapted for Docusaurus light and dark themes
> Overall corrections post-migration

- versioned_docs/version-5.3/04.navigation/01.navigation/01.navigation.md
- versioned_docs/version-5.3/05.policy/05.networkrules/05.networkrules.md
The PR #74 targeted only `next`. The changes have been applied to the current version, 5.3.
> Applied #74 changes to v5.3 (current)

- static/CNAME
The CNAME file is required by Github Pages for the configuration of the DNS alias: open-docs.neuvector.com.
> Added CNAME file

- docs/14.releasenotes/01.5x/01.5x.md
- docusaurus.config.js
- js-libs/variables.js
- js-libs/versions.js
- variables.json
- versioned_docs/version-5.3/14.releasenotes/01.5x/01.5x.md
The Docusaurus preprocessor global variables have been configured and are ready to use.
The first use-case, serving as an example, is the CVE impact levels, used in the Release Notes.
> Configured global variables

- versioned_docs/version-5.2/01.basics/01.basics.md
- versioned_docs/version-5.3/01.basics/01.basics.md
The versions 5.2 and 5.3 had a duplicate title in the welcome page. The duplicate title has been removed.
> Removed duplicate titles

- docs/02.deploying/01.production/02.operators/02.operators.md
- versioned_docs/version-5.2/02.deploying/01.production/02.operators/02.operators.md
- versioned_docs/version-5.3/02.deploying/01.production/02.operators/02.operators.md
Previous linked `https://catalog.redhat.com/software/operators/search?q=neuvector` redirects to `https://catalog.redhat.com/search?searchType=software&deployed_as=Operator` which gives 289 results and isn't narrowed down to `NeuVector`. 
The proposed new link `https://catalog.redhat.com/search?searchType=software&deployed_as=Operator&partnerName=NeuVector&p=1` behaves as the old one and returns two results published by NeuVector.
> fix: Link to Red Hat Certified Operator updated, previous one was broken.

- docs/12.troubleshooting/01.troubleshooting/01.troubleshooting.md
- versioned_docs/version-5.2/12.troubleshooting/01.troubleshooting/01.troubleshooting.md
- versioned_docs/version-5.3/12.troubleshooting/01.troubleshooting/01.troubleshooting.md
Fixes #94
As stated in the issue, `controller` was wrongly referenced instead of `scanner`.
> Corrected typo

- docs/02.deploying/01.production/04.internal/04.internal.md
- versioned_docs/version-5.3/02.deploying/01.production/04.internal/04.internal.md
The documentation on `Replacing Certificates Used in Internal Communications of NeuVector` has been updated with the addition of SANs.
Based on the scenario the users might have, the documentation has been split in 3 distinct parts.
> Updated replacing certificates for internal communications

- docs/06.scanning/06.scanners/06.scanners.md
When doing a standalone scan and using `CLUSTER_JOIN_ADDR` to submit scan results back to the NeuVector Controller API, the authentication fails because of a missing user and password. The relevant env vars `SCANNER_CTRL_API_USERNAME` and `SCANNER_CTRL_API_PASSWORD` are not mentioned in the documentation. They are only mentioned in a changelog entry: https://open-docs.neuvector.com/releasenotes/4x/#scanner-details.
This PR adds the information about them and what they are used for to the scanner usage description.
> docs(scanners): Add information about env vars to authenticate with nv controller api

- docs/14.releasenotes/01.5x/01.5x.md
- versioned_docs/version-5.4/02.deploying/02.kubernetes/02.kubernetes.md
- versioned_docs/version-5.4/02.deploying/04.openshift/04.openshift.md
I have added multiple changes in v5.4.0 documentation. Here are those
1. Completed the bash code block for v5.4.0 workaround. Releases below v5.4.0 are wrapped inside the workaround code block
2. Updated Native K8s deployment instructions for NV YAML deployment. This PR from manifest should be merged https://github.com/neuvector/manifests/pull/39 in order this instructions to work.
3. Updated Openshift deployment instructions for NV
> Multiple changes for v5.4.0 documentation

- versioned_docs/version-5.2/02.deploying/02.kubernetes/02.kubernetes.md
- versioned_docs/version-5.4/02.deploying/02.kubernetes/02.kubernetes.md
The link to `production` page from `kubernetes` page under deployment section was not working.
The link needed to be updated, and a typo at the headers page level was also impacting the build.
> Links to production page updated

- docs/05.policy/08.responserules/08.responserules.md
Address groups like criteria of address=x.x.x.x/x is not supported for matching.
> Update 08.responserules.md - clarify response rule group supported

- docs/02.deploying/06.public-cloud/01.awsmarketplace/01.awsmarketplace.md
- docs/02.deploying/06.public-cloud/02.azuremarketplace/02.azuremarketplace.md
- docs/02.deploying/06.public-cloud/03.marketplace-faq/03.marketplace-faq.md
- docs/02.deploying/06.public-cloud/06.public-cloud.md
Moved all pages related to deploying in a public cloud under a single point in the deploying section. 
Minor tweaks to text to fix links and routing.
> Restructure public cloud deploy section

- docs/05.policy/13.usingcrd/13.usingcrd.md
- versioned_docs/version-5.4/05.policy/13.usingcrd/13.usingcrd.md
Adding information for NvAdmissionControlSecurityRule CRD regarding generating sample CRD manifest, and also added relative links to inline documentation for context. Tied to Jira NVSHAS-9483.
> NVSHAS 9483 - Updating CRD NvAdmissionControlSecurityRule

- docs/02.deploying/01.production/01.configmap/01.configmap.md
- docs/11.automation/02.automation/02.automation.md
- versioned_docs/version-5.4/02.deploying/01.production/01.configmap/01.configmap.md
- versioned_docs/version-5.4/11.automation/02.automation/02.automation.md
Adding documentation for the Federated ConfigMap primary and managed clusters. Also updated the latest ConfigMap link to https://raw.githubusercontent.com/neuvector/manifests/main/kubernetes/5.4.0/initcfg.yaml, and updated the sample `initcfg.yaml`. Related to NVSHAS-5843.
> [NVSHAS-5843] Adding Documentation for Federated ConfigMap YAML

- docs/02.deploying/03.rancher/03.rancher.md
- versioned_docs/version-5.4/02.deploying/03.rancher/03.rancher.md
Adding documentation of mapped permission resources associated with NeuVector/Rancher SSO. Tied to NVSHAS-9680.
> [NVSHAS-9680] Adding NeuVector/Rancher SSO Permission Resources Documentation

- docs/07.reporting/01.reporting/01.reporting.md
- versioned_docs/version-5.2/07.reporting/01.reporting/01.reporting.md
- versioned_docs/version-5.3/07.reporting/01.reporting/01.reporting.md
- versioned_docs/version-5.4/07.reporting/01.reporting/01.reporting.md
Adding note to "Security Events" section on not using the catch-all character `(*)` when adding a whitelist rule as unexpected processes could be flagged causing process violations. Tied to NVSHAS-8911.
> [NVSHAS-8911] Security Events Note

- docs/02.deploying/01.production/04.internal/04.internal.md
- versioned_docs/version-5.2/02.deploying/01.production/04.internal/04.internal.md
- versioned_docs/version-5.3/02.deploying/01.production/04.internal/04.internal.md
- versioned_docs/version-5.4/02.deploying/01.production/04.internal/04.internal.md
Update internal certificate related document. 
Note: This should only be merged after 5.4.2 is released.
> fix: update internal certificate documents

- docs/06.scanning/01.scanning/01.scanning.md
- docs/06.scanning/01.scanning/02.compliance/02.compliance.md
- versioned_docs/version-5.4/06.scanning/01.scanning/01.scanning.md
- versioned_docs/version-5.4/06.scanning/01.scanning/02.compliance/02.compliance.md
Updating the community documentation wrt to compliance templates available. Removing NIST as was removed in NV v5.4.0 release. Tied to NVSHAS-8799, NVSHAS-6955, and NVSHAS-7945.
Updated in product-docs: https://github.com/rancher/neuvector-product-docs/pull/21
> [NVSHAS-8799, NVSHAS-6955, NVSHAS-7945] Updating Prime Compliance - 5.4

- docs/05.policy/13.usingcrd/13.usingcrd.md
- versioned_docs/version-5.4/05.policy/13.usingcrd/13.usingcrd.md
Updating the CRD page with new v5.4.3 feature `name_referral` and NvGroupDefinition CRD. Tied to [NVSHAS-9871] and [NVSHAS-4717].
The main content additions are under the headers "### NvGroupDefinition" and "#### Schema Attribute: `name_referral`". The page headers had to be adjusted as well as the right-side navigation was not displaying items that were too deeply nested.
> [5.4.3] Feature Update - name_referral

- docs/06.scanning/03.build/01.jenkins/01.jenkins.md
- versioned_docs/version-5.4/06.scanning/03.build/01.jenkins/01.jenkins.md
Updating the NV Jenkins Plugin page with new concurrent scanning support with API Key mode. Tied to issue https://github.com/neuvector/docs/issues/169.
> Updating NV Jenkins Plugin 2.5+ Features

- docs/07.reporting/01.reporting/01.reporting.md
- versioned_docs/version-5.2/07.reporting/01.reporting/01.reporting.md
- versioned_docs/version-5.3/07.reporting/01.reporting/01.reporting.md
- versioned_docs/version-5.4/07.reporting/01.reporting/01.reporting.md
The link for the file access rules for security policies still link to the previous `docs` subdomain which is inactive.
Updated in the old 5.x versioned documentation as well.
> Update the link to the file access rules

- docs/01.basics/02.requirements/02.requirements.md
- versioned_docs/version-5.4/01.basics/02.requirements/02.requirements.md
Adding workaround for large host environments, tied to SURE-10116.
Product PR: https://github.com/rancher/neuvector-product-docs/pull/32
> Adding workaround for large host environments

- docs/14.releasenotes/01.5x/01.5x.md
- versioned_docs/version-5.4/14.releasenotes/01.5x/01.5x.md
Adding information to 5.4 release note on DISA STIG Prime availability to clarify for users. In the 5.4 usage documentation, DISA STIG is stated to be for Prime users only. @selvamt94 could you please verify and thank you in advance!
> Update NV 5.4 Release Note - DISA STIG

- docs/02.deploying/10.remove/10.remove.md
- versioned_docs/version-5.4/02.deploying/10.remove/10.remove.md
Updating 'Resetting Admin Password' section. With v5.4.3 pod security hardening disabling Bash access by default an extra step was needed to disable this protection and allow access for resetting purposes. Tied to NVSHAS-9961.
> [NVSHAS-9961] Updating 'Resetting Admin Password' Section
