neuvector/docs

user/pages/03.configuration/01.console/01.replacecert/docs.md
=> Support chained certificates

user/pages/03.configuration/01.console/01.replacecert/docs.md
Updating TLS secrets with Helm.
=> Updating TLS secrets with Helm.

user/pages/08.integration/07.openid/docs.md
Updated "groupMembershipClaims" to "All" --> groupMembershipClaims" to "Application Group"
=> Update OIDC groupMembershipClaims default to Application Group

user/pages/02.deploying/01.production/04.internal/docs.md
Just adding a section for using helm to install/update the internal certificates
=> added helm info for the internal cert doc

.gitignore, .htaccess, Dockerfile, Makefile
This adds a Dockerfile and a make target to easily run the docs locally in Docker for local development.
=> Make it easier to run the docs for local development

user/pages/05.policy/03.admission/docs.md
Change wording to recommend using [dynamic admission control](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/), which is described in its following sections, instead of [static one](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#how-do-i-turn-on-an-admission-controller) used in api server argument to avoid confusion.
The docs is edited on GitHub directly and GitHub automatically converts a few EOL characters.  The real change is as below:
```
This feature is supported in Kubernetes 1.9+ and Openshift 3.9+. Before using the Admission Control function in NeuVector, there are two values that need to be set in the --admission-control argument passed to the cluster apiserver. Please see Kubernetes and Openshift sections …
```
=> Change wording in admission control docs

user/pages/02.deploying/07.publick8s/docs.md
Add EKS-A Snowball Edge validation.
=> Update docs.md with EKS-A Snowball Edge validation

user/pages/05.policy/03.admission/docs.md
Fixed Admission Control indication.
=> Fixed the location of the Admission Control within the NeuVector UI

user/pages/02.deploying/02.kubernetes/docs.md
=> Clarify steps/order for upgrades

user/pages/14.releasenotes/01.5x/docs.md
=> Added 5.3.1 release notes

docs/14.releasenotes/01.5x/01.5x.md, versioned_docs/version-5.3/14.releasenotes/01.5x/01.5x.md
=> Added v5.2.4-s3 release notes

package.json, yarn.lock
Release notes can be found [here](https://docusaurus.io/blog/releases/3.3)
=> Updated Docusaurus to v3.3

docs/14.releasenotes/01.5x/01.5x.md, versioned_docs/version-5.3/14.releasenotes/01.5x/01.5x.md
The release notes have been added to `Next` and `5.3` versions.
=> Added 5.3.3 release notes

versioned_docs/version-5.3/08.integration/06.adfs/06.adfs.md
The PR #99 only added the modifications to `06.adfs.md` in `/docs`.
Added the modifications into the version 5.3.
=> Added 06.adfs.md to version 5.3

docs/13.special/03.public-cloud/03.public-cloud.md, versioned_docs/version-5.3/13.special/03.public-cloud/03.public-cloud.md
The FAQ concerning the public clouds marketplace (AWS & Azure) has been placed under the `Special` section.
This is complementary to the AWS & Azure docs (under `Deploying`).
=> Added public cloud marketplace faq

docs/14.releasenotes/01.5x/01.5x.md, variables.json, versioned_docs/version-5.3/14.releasenotes/01.5x/01.5x.md
The visuals for CVEs levels have been updated to include `Critical`.
=> Added v5.2.4-s5 to Release Notes

docs/14.releasenotes/01.5x/01.5x.md, versioned_docs/version-5.3/14.releasenotes/01.5x/01.5x.md
Both the the `5.3` and `Next` versions are updated.
=> Added the v5.3.4 release notes

.github/workflows/deploy.yaml
Updating the action to remove unauthorized action and update to v4.
=> Update Actions/Deploy Workflow

.github/workflows/deploy.yaml
Removing the token to resolve the build error being seen.
=> Fix actions

.github/workflows/deploy.yaml
Updating deployment job with necessary permissions and id after removing unauthorized action.
=> Updating deploy.yaml

docs/01.basics/02.requirements/02.requirements.md
=> Requirements note about Multus support

docs/01.basics/01.basics.md, docs/14.releasenotes/01.5x/01.5x.md, versioned_docs/version-5.4/01.basics/01.basics.md, versioned_docs/version-5.4/14.releasenotes/01.5x/01.5x.md
Adding v5.4.1 release notes and updating basics page example to use latest v5.4.1 release.
=> Adding v5.4.1 Release Notes/Updating Basics Page

versioned_docs/version-5.4/02.deploying/01.production/03.details/03.details.md
=> Sync Note v5.4 - Manager_SSL

versioned_docs/version-5.4/02.deploying/01.production/04.internal/04.internal.md
Adding internal.md page update to v5.4 from /docs.
=> Syncing Internal Page - v5.4

versioned_docs/version-5.4/08.integration/12.rancher_sso_rbac.md
Adding documentation file versioned_docs/version-5.4/08.integration/12.rancher_sso_rbac.md as requested by @sunilarjun. Thanks.
=> Add documentation 12.rancher_sso_rbac.md to versioned docs

docs/05.policy/14.namespaceboundary/14.namespaceboundary.md, versioned_docs/version-5.4/05.policy/14.namespaceboundary/14.namespaceboundary.md
Syncing with 5.4 usage document, tied to NVSHAS-8325.
=> [NVSHAS-8325] Sync Page "Policy: Namespace Boundary Enforcement" - 5.4

docs/03.configuration/01.console/01.console.md, versioned_docs/version-5.4/03.configuration/01.console/01.console.md
Adding bootstrap password instructions, tied to NVSHAS-8773 and 5.4 new feature usage.
=> [NVSHAS-8773] Adding Bootstrap Password Instructions - 5.4

docs/12.troubleshooting/01.troubleshooting/01.troubleshooting.md, versioned_docs/version-5.4/12.troubleshooting/01.troubleshooting/01.troubleshooting.md
Adding in log level support to troubleshooting page per usage document. Tied to NVSHAS-7687.
=> [NVSHAS-7687] Log Level Support - 5.4

docs/14.releasenotes/01.5x/01.5x.md, versioned_docs/version-5.4/14.releasenotes/01.5x/01.5x.md
=> NeuVector 5.4.2 Release Notes

versioned_docs/version-5.4/14.releasenotes/01.5x/01.5x.md
Added additional note about helm
=> 5.4.2 release notes update

docs/02.deploying/02.kubernetes/02.kubernetes.md, docs/02.deploying/04.openshift/04.openshift.md, versioned_docs/version-5.4/02.deploying/02.kubernetes/02.kubernetes.md, versioned_docs/version-5.4/02.deploying/04.openshift/04.openshift.md
Below YAML files are changes,
- K8s Installation YAML
- OC Installation YAML
=> Version change and creation of clusterrole/clusterrolebinding for new CRD feature 4717

docs/05.policy/06.processrules/06.processrules.md, versioned_docs/version-5.4/05.policy/06.processrules/06.processrules.md
[NVSHAS-9890](https://jira.suse.com/browse/NVSHAS-9890)
[Documentation] Need to add note for Zero-drift Process Protection
=> NVSHAS-9890 [Documentation] Need to add note for Zero-drift Process Protection

docs/14.releasenotes/01.5x/01.5x.md, versioned_docs/version-5.4/14.releasenotes/01.5x/01.5x.md
Adding the [v5.4.3 release notes](https://github.com/neuvector/neuvector/releases/tag/v5.4.3) to the Community docs.
=> v5.4.3 Release Notes

docs/06.scanning/02.registry/02.registry.md, versioned_docs/version-5.4/06.scanning/02.registry/02.registry.md
Hello @sunilarjun, this update is for new scan option (Github Container Registry)
Please help to review.
=> [NVSHAS-7997] Add GHCR scan desc

docs/06.scanning/03.build/01.jenkins/01.jenkins.md, versioned_docs/version-5.2/06.scanning/03.build/01.jenkins/01.jenkins.md, versioned_docs/version-5.3/06.scanning/03.build/01.jenkins/01.jenkins.md, versioned_docs/version-5.4/06.scanning/03.build/01.jenkins/01.jenkins.md
General style and grammar edits.
=> General Style/Grammar Edits - Jenkins Page

CODEOWNERS
Adding CODEOWNERS file per Slack thread.
=> Adding CODEOWNERS File

docs/14.releasenotes/01.5x/01.5x.md, versioned_docs/version-5.4/14.releasenotes/01.5x/01.5x.md
Adding v5.4.4 NeuVector release note.
References slack PDF/MD file
=> Adding v5.4.4 NeuVector release note.
